export const SIGN_UP = 'SIGN_UP'
export const USER_ERROR = 'USER_ERROR'
export const USER_DASHBOARD = 'USER_DASHBOARD'
export const SIGN_IN = 'SIGN_IN'
export const LOGGED_IN = 'LOGGED_IN'
export const LOGGED_OUT = 'LOGGED_OUT'
